Mov 15 16 valid user user profile
Sergey113222/Cinema-base pull request #12
Opened 2021-05-13 15:21 UTC by Denisyasyuchenya

Mov-15-16. Please tell me what I should add.

2021-05-20 19:47 UTC, RomanKashenok commented
ты уверен, что мержить надо в мастер?

2021-05-21 14:04 UTC, Denisyasyuchenya commented
I have changed the base branch from master to development!

2021-05-30 13:48 UTC, RomanKashenok requested changes

2021-05-30 13:48 UTC, RomanKashenok commented on src/main/java/info/movietrash/cinemabase/model/Profile.java
> +import javax.validation.constraints.*;
try not to use import with '*'

2021-05-30 13:48 UTC, RomanKashenok commented on src/main/java/info/movietrash/cinemabase/model/Profile.java
> +    @Max(value = 99, message = "Age should not be greater than 99")
why min and max instead of @Size ?

2021-05-30 13:48 UTC, RomanKashenok commented on src/main/java/info/movietrash/cinemabase/model/User.java
> +    @NotNull
@NotEmpty already contain @NotNull check

2021-05-30 13:48 UTC, RomanKashenok commented on src/main/java/info/movietrash/cinemabase/model/User.java
>      @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
Why do you need profile here if you have no access to it?  and never use it?

2021-07-04 20:01 UTC, merged